# Generated by Django 5.1.15 on 2026-08-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('coordinador', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'verbose_name': 'entidad',
                'verbose_name_plural': 'entidades',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UnidadMedica',
            fields=[
                ('clues', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_unidad_medica', models.CharField(blank=True, max_length=50)),
                ('municipio', models.CharField(blank=True, max_length=100)),
                ('origen', models.CharField(choices=[('catalogo_mensual', 'Catálogo mensual (CLUES_IMB.xlsx)'), ('manual', 'Capturado manualmente')], default='manual', max_length=20)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidades_medicas', to='catalogos.entidad')),
            ],
            options={
                'verbose_name': 'unidad médica',
                'verbose_name_plural': 'unidades médicas',
                'ordering': ['entidad', 'nombre'],
            },
        ),
    ]
