# Generated by Django 5.1.15 on 2026-08-25 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidadmedica',
            name='nivel_atencion',
            field=models.CharField(choices=[('PRIMER NIVEL', 'Primer nivel'), ('SEGUNDO NIVEL', 'Segundo nivel'), ('TERCER NIVEL', 'Tercer nivel')], default='PRIMER NIVEL', max_length=20),
        ),
    ]
