# Generated by Django 5.1.15 on 2026-08-26 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_unidadmedica_nivel_atencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedica',
            name='tipo_unidad_medica',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
