# Generated by Django 5.1.15 on 2026-08-25 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicomovimientos',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='historicomovimientos',
            index=models.Index(fields=['content_type', 'object_id'], name='historico_h_content_8d4f21_idx'),
        ),
    ]
