# Generated by Django 5.1.15 on 2026-08-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('foto', 'Foto'), ('video', 'Video'), ('pdf', 'PDF'), ('documento', 'Documento')], max_length=20)),
                ('archivo', models.FileField(upload_to='evidencias/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'archivo de evidencia',
                'verbose_name_plural': 'archivos de evidencia',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregado', models.BooleanField(default=False)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('programacion_visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entrega', to='programacion.programacionvisita')),
            ],
            options={
                'verbose_name': 'entrega',
                'verbose_name_plural': 'entregas',
                'ordering': ['-fecha_entrega'],
            },
        ),
    ]
