# Generated by Django 5.1.15 on 2026-08-28 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entregas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenciaarchivo',
            name='archivo',
        ),
        migrations.AddField(
            model_name='evidenciaarchivo',
            name='nombre_original',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidenciaarchivo',
            name='ruta_almacen',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidenciaarchivo',
            name='subido_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='evidencias_subidas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
