# Generated by Django 5.1.15 on 2026-08-25 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ordinaria', 'Ordinaria'), ('extraordinaria', 'Extraordinaria'), ('emergencia', 'Emergencia')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estatus', models.CharField(choices=[('planeada', 'Planeada'), ('en_curso', 'En curso'), ('cerrada', 'Cerrada'), ('cancelada', 'Cancelada')], default='planeada', max_length=20)),
            ],
            options={
                'verbose_name': 'jornada',
                'verbose_name_plural': 'jornadas',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_o_nombre', models.CharField(max_length=50)),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rutas', to='catalogos.entidad')),
                ('jornada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='programacion.jornada')),
            ],
            options={
                'verbose_name': 'ruta',
                'verbose_name_plural': 'rutas',
                'ordering': ['jornada', 'entidad', 'numero_o_nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProgramacionVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_distribucion_programada', models.DateField()),
                ('claves_a_desplazar', models.PositiveIntegerField(default=0)),
                ('piezas_medicamento', models.PositiveIntegerField(default=0)),
                ('piezas_material_curacion', models.PositiveIntegerField(default=0)),
                ('tipo_unidad_medica', models.CharField(blank=True, max_length=50)),
                ('quien_recibe', models.CharField(blank=True, max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('bloqueada', models.BooleanField(default=False)),
                ('unidad_medica', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visitas_programadas', to='catalogos.unidadmedica')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='programacion.ruta')),
            ],
            options={
                'verbose_name': 'programación de visita',
                'verbose_name_plural': 'programaciones de visita',
                'ordering': ['ruta', 'unidad_medica'],
            },
        ),
    ]
