# Generated by Django 5.1.15 on 2026-08-25 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jornada',
            name='categoria',
            field=models.CharField(choices=[('primer_nivel', 'Primer nivel'), ('segundo_tercer_nivel', 'Segundo y tercer nivel')], default='primer_nivel', max_length=25),
        ),
    ]
