# Generated by Django 5.1.15 on 2026-08-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programacion', '0005_endurecer_jornada_en_programacionvisita'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jornada',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'distribución', 'verbose_name_plural': 'distribuciones'},
        ),
    ]
